Recommendation&Trend
Neliitsme/Recommendation-Service pull request #10
Opened 2022-12-02 11:55 UTC by maypink

WIP

2022-12-02 16:11 UTC, maypink commented
что-то не доделано, но общий вектор такой. меня больше всего смущает эта заплатка с Order, кажется, она должна выглядеть иначе

2022-12-02 17:14 UTC, Neliitsme commented
Так, смотрю сейчас на скорую руку, позже еще гляну, но я не понял зачем ты сделала класс Order, мы же не отвечаем за него, это работа другого сервиса. Или у тебя какое-то свое видение?

2022-12-02 20:15 UTC, lehatheslayer reviewed
в основном по стилю комментарии

2022-12-02 20:15 UTC, lehatheslayer commented on src/main/kotlin/com/itmo/se/recommendationservice/recommendations/logic/Recommendation.kt
>      var seenCategories: MutableMap<UUID, SeenCategory> = mutableMapOf()
не хотим тут сделать поля приватными или это так и задумано?

2022-12-02 20:16 UTC, fedos3d commented on src/main/kotlin/com/itmo/se/recommendationservice/trends/controller/TrendController.kt
> +    fun getAllTrendingItems()  {
Можно просто линтер накатить на GH actions

2022-12-02 20:16 UTC, fedos3d commented on src/main/kotlin/com/itmo/se/recommendationservice/recommendations/api/RecommendationEvents.kt
> +    Event<RecommendationAggregate>(name = USER_SEEN_ITEM_COEFFICIENT_DECREASED)
linter

2022-12-02 20:33 UTC, lehatheslayer commented on src/main/kotlin/com/itmo/se/recommendationservice/trends/controller/TrendController.kt
> +    fun getAllTrendingItems()  {
> Можно просто линтер накатить на GH actions

накати

2022-12-02 20:34 UTC, Neliitsme requested changes
Прочитай комменты которые я оставил

2022-12-02 20:34 UTC, Neliitsme commented on src/main/kotlin/com/itmo/se/recommendationservice/trends/controller/TrendController.kt
> +class TrendController( val trendEsService: EventSourcingService<UUID, TrendAggregate, Trend>
Я ставил под большое сомнение создание контроллера для трендов. В каком-то смысле он нужен, в каком-то смысле юзаем его только мы. Можно оставить.

2022-12-02 21:56 UTC, Neliitsme commented on src/main/kotlin/com/itmo/se/recommendationservice/trends/controller/TrendController.kt
> +    fun getAllTrendingItems()  {
Либо можно не накатывать, а потом отформатировать код в идее. Причем можно весь, лишним не будет

2022-12-02 22:04 UTC, Neliitsme commented on src/main/kotlin/com/itmo/se/recommendationservice/recommendations/logic/Recommendation.kt
>      var seenCategories: MutableMap<UUID, SeenCategory> = mutableMapOf()
Так и задумано, думаю не стоит

2022-12-03 10:04 UTC, Neliitsme commented
Я отрефакторил код, отформатировал, добавил обработку эдж кейсов. Пока приму пр, но нужно будет чтобы ты объяснила ход своих мыслей

2022-12-03 10:10 UTC, Neliitsme approved these changes

2022-12-03 10:11 UTC, merged